Update database.go
GroupHistoryProject/History-BackEnd pull request #1
Opened 2023-11-16 11:59 UTC by aleksandra0KR

feat: registration with validity checks

2023-11-16 12:20 UTC, lilpipidron requested changes

2023-11-16 12:20 UTC, lilpipidron commented on internal/database/database.go
> +}
Разбей на отдельные функции, разнеси логически по файлам, все handle функции должны лежать в handl'ах
Все работа с бд должна быть отделена от handle
я вижу тут много парса, вынеси в отдельную дирректорию parse и там напиши необхожимые функкции, пусть даже они будут в две строчки

2023-11-16 12:20 UTC, lilpipidron commented on internal/database/database.go
>  	}
думаю, проверку есть ли юзер, можно вынести в отедльную функцию для удобства и упрощения дэбага

2023-11-16 12:20 UTC, lilpipidron commented on internal/database/database.go
>  }
чет очень сложно выглядит, мне кажется мой вариант был бы лучше

2023-11-16 12:34 UTC, zzucch requested changes

2023-11-16 12:34 UTC, zzucch commented on internal/database/database.go
> +	// провреяем есть ли пользователь
Перевести тут и в остальных местах на английский коммент

2023-11-16 12:34 UTC, zzucch commented on internal/database/database.go
> +		// есть прописные буквы
Тут и без комментариев очевидно что делается, убери их

2023-11-16 12:34 UTC, zzucch commented on internal/database/database.go
> +	// проверка длины имени пользлвателя
Вынеси магические числа в константы

2023-11-16 12:34 UTC, zzucch commented on internal/database/database.go
> +		tpl.ExecuteTemplate(w, "register.html", "Пожалуйства проверьте критерии для фамилии пользователя")
"пожалуйста,"

2023-11-16 12:34 UTC, zzucch commented on internal/database/database.go
> +		if unicode.IsLetter(char) == false {
Заменить '== false' на '!' здесь и в остальных местах

2023-11-16 12:34 UTC, zzucch commented on internal/database/database.go
> +	fmt.Fprint(w, "congrats, your account has been successfully created")
'congrats' -> congratulations?

2023-11-16 15:20 UTC, zzucch requested changes

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +	fmt.Println("*****registerHandler running*****")
может быть тут и в остальных местах будет лучше использовать log.Print а не fmt.Print?

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +	tpl.ExecuteTemplate(w, "main.html", nil)
обработай ошибку

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +
убери пустую строку

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +	r.ParseForm()
обработай ошибку

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +		tpl.ExecuteTemplate(w, "register.html", "Пожалуйства проверьте критерии для имени пользователя")
обработай ошибку

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +	usersurname := r.FormValue("usersurname")
usersurname -> surname

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +		tpl.ExecuteTemplate(w, "register.html", "Пожалуйства проверьте критерии для фамилии пользователя")
обработай ошибку

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +		tpl.ExecuteTemplate(w, "register.html", "Пожалуйства проверьте критерии для логина")
обработай ошибку

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +	var pswdLowercase, pswdUppercase, pswdNumber, pswdSpecial, pswdLength, pswdNoSpaces bool
может быть будет лучше сделать pswd -> pwd?

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +		tpl.ExecuteTemplate(w, "register.html", "Пожалуйства проверьте критерии для пароля")
обработай ошибку

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +		tpl.ExecuteTemplate(w, "register.html", "Такое имя пользователя уже есть")
обработай ошибку

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +var db *sql.DB
не используешь, а потом shadow-ишь на строке 142

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +	if err != sql.ErrNoRows {
замени '!=' на 'errors.Is()'

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +		fmt.Println("Openning DB Error:")
openning -> opening

2023-11-16 15:20 UTC, zzucch commented on internal/database/database.go
> +	defer insertStmt.Close()
обработай ошибку

2023-11-20 10:11 UTC, lilpipidron requested changes

2023-11-20 10:11 UTC, lilpipidron commented on internal/database/registerAuthHandler.go
> +	fmt.Fprint(w, "congrats, your account has been successfully created")
Валидацию в другой файлик
validators/validation.go
DRY мне показался тут имеется в твоих проверках

2023-11-21 13:33 UTC, zzucch requested changes

2023-11-21 13:33 UTC, zzucch commented on internal/database/AddUser.go
> +		panic(err.Error())
убери панику

2023-11-21 13:33 UTC, zzucch commented on internal/database/database.go
> +		panic(err.Error)
панику убери

2023-11-22 09:59 UTC, zzucch approved these changes

2023-11-22 10:00 UTC, lilpipidron approved these changes

2023-11-22 10:01 UTC, merged